import { JSX } from 'react';

// Identity pixel icons for the menu gadgets (docs/style-guide.md): the
// disk and the paintbrush, drawn as ASCII maps rendered to crispEdges SVG
// rects. Action glyphs (the transforms) are line drawings in
// transformIcons.tsx, not pixel art. 'X' renders in currentColor should a
// map ever need to follow the gadget text color.
//
// The four below are the app's own theme colors and the whole vocabulary
// available to a map - every icon here is drawn from exactly these, so the
// icons read as one set with the rest of the chrome. Near-misses have been
// through here before (an #0a0a28 "icon navy" beside black, a #0000ff blue
// beside the Workbench one) and only ever amounted to two inks that looked
// the same at icon size while quietly widening the palette. Blue and orange
// are literal copies rather than the --wb-* custom properties every
// stylesheet uses (index.css): these feed SVG `fill` presentation
// attributes, which don't resolve var(). Keep them in step with index.css.
const PALETTE: Record<string, string> = {
  K: 'black', // ink: outlines, bodies, shadows
  W: '#ffffff',
  B: 'rgb(0, 85, 170)', // Workbench blue, = --wb-blue
  O: '#ff8800', // Workbench orange, = --wb-orange
};

function parse(map: string): string[] {
  return map
    .trim()
    .split('\n')
    .map((row) => row.trim());
}

export function PixelIcon({ map, scale = 2 }: { map: string; scale?: number }): JSX.Element {
  const rows = parse(map);
  const height = rows.length;
  const width = rows[0].length;
  return (
    <svg
      className="pixel-icon"
      width={width * scale}
      height={height * scale}
      viewBox={`0 0 ${width} ${height}`}
      shapeRendering="crispEdges"
      aria-hidden="true"
      focusable="false"
    >
      {rows.flatMap((row, y) =>
        row.split('').flatMap((char, x) => {
          if (char === '.') {
            return [];
          }
          const fill = char === 'X' ? 'currentColor' : PALETTE[char];
          return [<rect key={`${x}-${y}`} x={x} y={y} width={1} height={1} fill={fill} />];
        })
      )}
    </svg>
  );
}

export const icons = {
  // The Workbench 1.3 disk, traced from the original icon: black body with the
  // chamfered top-right corner, orange shutter with its dark window, the
  // striped orange/blue Workbench peak on the white label, and the
  // write-protect notch at bottom-left. Currently unused - it is the faithful
  // full-resolution copy the Open/Save pair below was drawn over.
  //
  // The source is a hires icon - 35x15 pixels that are twice as tall as they
  // are wide (Workbench ran at 640x256). Every row is therefore doubled here,
  // which is what the Amiga's own display did: 35x30 square pixels, the same
  // picture at the right proportions with none of the horizontal detail
  // (those 1px stripes) lost to squeezing it back down.
  disk: `
    KKKKKKKKKOOOOOOOOOOOOOOOOOKKKKKKK..
    KKKKKKKKKOOOOOOOOOOOOOOOOOKKKKKKK..
    KKKKKKKKKOOOOOOOOOOKKKKOOOKKKKKKKK.
    KKKKKKKKKOOOOOOOOOOKKKKOOOKKKKKKKK.
    KKKKKKKKKOOOOOOOOOOKKKKOOOKKKKKKKKK
    KKKKKKKKKOOOOOOOOOOKKKKOOOKKKKKKKKK
    KKKKKKKKKOOOOOOOOOOKKKKOOOKKKKKKKKK
    KKKKKKKKKOOOOOOOOOOKKKKOOOKKKKKKKKK
    KKKKKKKKKOOOOOOOOOOOOOOOOOKKKKKKKKK
    KKKKKKKKKOOOOOOOOOOOOOOOOOKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKWWWWWWWKOKOKOKWKBKWWWWKKKKKKK
    KKKKKKWWWWWWWKOKOKOKWKBKWWWWKKKKKKK
    KKKKKKWWWWWWKOKWKOKBKWKBKWWWWKKKKKK
    KKKKKKWWWWWWKOKWKOKBKWKBKWWWWKKKKKK
    KKKKKKWWWWWKOKWKOKWKBKWKBKWWWKKKKKK
    KKKKKKWWWWWKOKWKOKWKBKWKBKWWWKKKKKK
    KKKKKKWWWWKOKWKOKWWWKBKWKBKWWKKKKKK
    KKKKKKWWWWKOKWKOKWWWKBKWKBKWWKKKKKK
    KKKKKKWWWKOKWKOKWWWWWWWWWWWWWKKKKKK
    KKKKKKWWWKOKWKOKWWWWWWWWWWWWWKKKKKK
    KKKKKKWWKOKWKOKWWWWWWWWWWWWWWKKKKKK
    KKKKKKWWKOKWKOKWWWWWWWWWWWWWWKKKKKK
    KKWWKKWKOKWKOKWWWWWWWWWWWWWWWKKKKKK
    KKWWKKWKOKWKOKWWWWWWWWWWWWWWWKKKKKK
    KKKKKKWWWWWWWWWWWWWWWWWWWWWWWKKKKKK
    KKKKKKWWWWWWWWWWWWWWWWWWWWWWWKKKKKK
  `,

  // Open/Save: the disk with an arrow on its label, hand-drawn over the trace
  // above and a little smaller than it (31x27), which sits closer to how the
  // original reads at icon size. The arrow keeps the label's own striped
  // diagonals rather than being a solid shape, and rises out of a tray for
  // Open / drops into one for Save. Each takes a single label color from the
  // two the original label carried - blue reading off the disk, orange
  // writing onto it - so direction and color say the same thing. Both render
  // at scale 2, so 62x54.
  diskLoad: `
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKK..
    KKKKKKKKOOOOOOOOOOOOOOOKKKKKK..
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKK.
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKK.
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKKK
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKKK
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKKK
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKKK
    KKKKKKKKOOOOOOOOOOOOOOOKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKWWWWWWWWWKWWWWWWWWWKKKKKK
    KKKKKKWWWWWWWWKBKWWWWWWWWWKKKKK
    KKKKKKWWWWWWWWKBKWWWWWWWWWKKKKK
    KKKKKKWWWWWWWKBKBKWWWWWWWWKKKKK
    KKKKKKWWWWWWWKBKBKWWWWWWWWKKKKK
    KKKKKKWWWWWWKBKBKBKWWWWWWWKKKKK
    KKKKKKWWWWWWKBKBKBKWWWWWWWKKKKK
    KKKKKKWWWWWKBWKBKWBKWWWWWWKKKKK
    KKKKKKWKKKWKBWKBKWBKWKKKWWKKKKK
    KKKKKKWKBKWWWWKBKWWWWKBKWWKKKKK
    KKKKKKWKBKKKKKKKKKKKKKBKWWKKKKK
    KK..KKWKBBBBBBBBBBBBBBBKWWKKKKK
    KK..KKWKKKKKKKKKKKKKKKKKWWKKKKK
    KKKKKKWWWWWWWWWWWWWWWWWWWWKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
  `,

  diskSave: `
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKK..
    KKKKKKKKOOOOOOOOOOOOOOOKKKKKK..
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKK.
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKK.
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKKK
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKKK
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKKK
    KKKKKKKKOOOOOOOKKKKOOOOKKKKKKKK
    KKKKKKKKOOOOOOOOOOOOOOOKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKWWWWWWWWKOKWWWWWWWWKKKKKK
    KKKKKKWWWWWKOWKOKWOKWWWWWWKKKKK
    KKKKKKWWWWWKOWKOKWOKWWWWWWKKKKK
    KKKKKKWWWWWWKOKOKOKWWWWWWWKKKKK
    KKKKKKWWWWWWKOKOKOKWWWWWWWKKKKK
    KKKKKKWWWWWWWKOKOKWWWWWWWWKKKKK
    KKKKKKWWWWWWWKOKOKWWWWWWWWKKKKK
    KKKKKKWWWWWWWWKOKWWWWWWWWWKKKKK
    KKKKKKWKKKWWWWKOKWWWWKKKWWKKKKK
    KKKKKKWKOKWWWWWKWWWWWKOKWWKKKKK
    KKKKKKWKOKKKKKKKKKKKKKOKWWKKKKK
    KK..KKWKOOOOOOOOOOOOOOOKWWKKKKK
    KK..KKWKKKKKKKKKKKKKKKKKWWKKKKK
    KKKKKKWWWWWWWWWWWWWWWWWWWWKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
  `,

  // Copy/Paste: the same 31x27 as the disks beside them, and the same rule
  // for direction — blue for what comes in, orange for what goes out.
  clipboardCopy: `
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKWWWWWWWWWWWWWWWWKKKK
    KKKKKKKKKKKWWWWWWWWWWWWWWWWKKKK
    KKKKKKKKKKKWWWWWWWWWWWWWWWWKKKK
    KKKKKKKKKKKWWWWWWWWWWWWWWWWKKKK
    KKKKKKKKKKKWWWWWWWWWWWWWWWWKKKK
    KKKKKKKKKKKWWWWWWWWWWWWWWWWKKKK
    KKKKKKKKKKKKKKKKKKKKKWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWKWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWKWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWKWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWKWWWWWWKKKK
    KKKKWWWOOOOOOOOOOWWWKWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWKWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWKWWWWWWKKKK
    KKKKWWWOOOOOOOOOOWWWKWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWKWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWKWWWWWWKKKK
    KKKKWWWOOOOOOOOOOWWWKWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWKKKKKKKKKKK
    KKKKWWWWWWWWWWWWWWWWKKKKKKKKKKK
    KKKKWWWOOOOOOOOOOWWWKKKKKKKKKKK
    KKKKWWWWWWWWWWWWWWWWKKKKKKKKKKK
    KKKKWWWWWWWWWWWWWWWWKKKKKKKKKKK
    KKKKWWWWWWWWWWWWWWWWKKKKKKKKKKK
    KKKKWWWWWWWWWWWWWWWWKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
  `,

  clipboardPaste: `
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKBBBBBBBKKKKKKKKKKKK
    KKKKKKKKKKKKBBBBBBBKKKKKKKKKKKK
    KKKKKKKKKKKKBBBBBBBKKKKKKKKKKKK
    KKKKWWWWWWWKBBBBBBBKWWWWWWWKKKK
    KKKKWWWWWWWKBBBBBBBKWWWWWWWKKKK
    KKKKWWWWWWWKKKKKKKKKWWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWWWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWWWWWWWWKKKK
    KKKKWWWWKKKKKKKKKKKKKKKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKWWBBBBBBBBBWWKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKWWBBBBBBBBBWWKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKWWBBBBBBBBBWWKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKWWWWWWWWWWWWWKWWWWKKKK
    KKKKWWWWKKKKKKKKKKKKKKKWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWWWWWWWWKKKK
    KKKKWWWWWWWWWWWWWWWWWWWWWWWKKKK
  `,

  // The paintbrush: orange bristles, Workbench blue handle, outlined in
  // black. The handle is deliberately the same blue as a pressed gadget's
  // ground, so on the pressed Brush gadget it reads as an outlined hollow
  // rather than a blue shape - its black outline still carries the
  // silhouette. That was tried as white instead, which survives all three
  // grounds (paper, pressed blue, hover orange), and blue simply looked
  // better everywhere else. Leave it blue.
  brush: `
    .............KKK
    ............KOOK
    ...........KOOK.
    ..........KOOK..
    .........KOOK...
    ........KOOK....
    .......KOOK.....
    ......KWKK......
    ...KKKKWWK......
    ..KKKKKKK.......
    .KBBKKKK........
    .KBBBKKK........
    .KBBBKKK........
    .KBBBBK.........
    KBBBKK..........
    KKKK............
  `,

  // The Deluxe Paint saved-picture icon: a framed desert-mountain landscape
  // (three peaks, snowcaps, a cloud band, scrubby orange foreground), traced
  // pixel-for-pixel from the original Workbench disk icon at its native
  // resolution (rather than up-scaled) so it stays crisp at the gadget's
  // scale=1 - the other maps here are small enough that scale=3 upscaling
  // doesn't show, this one is already full-size.
  image: `
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKK
    KKWKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKWKK
    KKWKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKWKK
    KKWKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKWKK
    KKWKKKBBBBBBBBBBBBBBBBBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKBBBBKKKWKK
    KKWKKKBBBBBBBBBBBBBBBBBBKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKBBBBKKKWKK
    KKWKKKBBBBBBBBBBBBBKKBBBBBBBBBBWWWWWWWWWWWWWWWWWBBBBBBBBBBBBKKKWKK
    KKWKKKBBBBBBBBBBBBBKKBBBBBBBBBBWWWWWWWWWWWWWWWWKBBBBBBBBBBBBKKKWKK
    KKWKKKBBBBBBBBBBKKKWWKBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBKKKWKK
    KKWKKKBBBBBBBBBBWKKWWKBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBKKKWKK
    KKWKKKBBBBBBBBBBWKKKWKBBBBBBBBBBBBKBBBBBBBBBBBBBBBKBBBBBBBBBKKKWKK
    KKWKKKBBBBBBBBBKWWKKWKBBBBBBBBBBBKKKBBBBBBBBBBBBBBWBBBBBBBBBKKKWKK
    KKWKKKBBBBBBBBBKWWKKWWBBBBBBBBBBBKKKBBBBBBBBBBBBBBWKBBBBBBBBKKKWKK
    KKWKKKBBBBBBBKKKWWOKWWWWBBBBBBBBKWWWKBBBBBBBBBKKKWWWWKBBBBBBKKKWKK
    KKWKKKBBBBBBBKKKKWOKWWWWBBBBBBBBKKWWKBBBBBBBBBKKKWWWWKBBBBBBKKKWKK
    KKWKKKBBBBBBBKKKKOWWWWWOOBBBBBBBKKKWWKBBBBBBKKKKKWWWWWWKBBBBKKKWKK
    KKWKKKBBBBBBKKKKKOWWWWWOOBBBBBBBKKKWWKBBBBBBKKKKKWWWWWWKBBBBKKKWKK
    KKWKKKBBBBBBKKKKKKKKKKKOOOBBBBBKKOOOOKKBBKKKKKWKKWWWWWWWKKBBKKKWKK
    KKWKKKBBBBBKKKKKKKKKKKKOOOBBBBBKKOOOOOKBBKKKKKWWWWWWWWWWWWBBKKKWKK
    KKWKKKBBBBKKKKKKKKKKKKKOOOKBBKKKKOOOOOKKKKKKKKKKKWKWWWWWWWKKKKKWKK
    KKWKKKBBBKKKKKOOKOOKOOKOOOOBBKKKKOKOOOOKKKKKKKKKKWKKWWWWWWWWKKKWKK
    KKWKKKBBBKKKKKOOKOOKOOKOOOOKKKKKKOKOOOOKKKKKKKKKKKKKWWWWWWWWKKKWKK
    KKWKKKBKKKKOOKKKKOKKOOKOOOOOKKKKKKOOOOOKKKKKKKKOKOKOOOOWWWWWKKKWKK
    KKWKKKBKKKKOOKKKKOKKOOKOOOOOKKKKKKOOOOOKKKKKKKKOKOKOOOOWWWWWKKKWKK
    KKWKKKKKKKKOOKKOKOOOOOOOOOOKKKKOOOOOKKKOKKOKKKOOKKKOOOOOWWWWKKKWKK
    KKWKKKKKKKKOOKKOKOOOOOOOOOOKKKKOOOOOKKKOKKOKKKOOKKKOOOOOWWWWKKKWKK
    KKWKKKKKKKKKKKKOOOOOOOOOKOOKKOKKOOOKKKKKKKKKKKKKKOOOOOOOOOOOKKKWKK
    KKWKKKKKKOKKKOKOOOOOOOOOKOKKKOOKOOOKOOKKKOKKKKKKKOOOOOOOOOOOKKKWKK
    KKWKKKKKKKKKKOKOOOOOOOOOKKKKOOOKOOOKKKKKKOKKKKKKKOOOOOOOOOOOKKKWKK
    KKWKKKKKKKKKKOOOOKOOOOOOOKKOOOOKOOKKKKKOOOKOOKKOKOOKKOOOOOOOKKKWKK
    KKWKKKKKKKKKKOOOOKOOOOOOOKKOOOOKOOKKKKKOOOKOOOKOKOOKOOOOOOOOKKKWKK
    KKWKKKKKKKOKKOKOKOOOOOOOOOOOKKOOOKOKKKOKOKOKOOOKKOOOOOOOOOOOKKKWKK
    KKWKKKKKKKOKKOKOKOOOOOOOOOOOKKOOOKOKKKOKOKOKOOOKKOOOOOOOOOOOKKKWKK
    KKWKKKKKKOOOKKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKKKWKK
    KKWKKKKKKOOOKKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKKKWKK
    KKWKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKWKK
    KKWKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKWKK
    KKWKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKWKK
    KKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKK
    KKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
  `,

  // The Workbench 1.3 Preferences icon: the three-panel keyboard unit (each
  // panel outlined, orange LEDs at the outer two, a dark slot in the right
  // one) under a big orange question mark whose stem runs down through it.
  // Traced from the original icon, then hand-tuned. Unlike `image` above it
  // renders at scale=2: 46x27 is small enough that doubling reads as
  // deliberate fat-pixel art rather than a blur, and it takes the icon to
  // 92x54, matching the visual weight of the disk/brush gadgets beside it
  // (the 64px gadget leaves 5px clearance at that height - going bigger
  // needs the row to grow, and a non-integer scale would break the even
  // pixel grid).
  prefs: `
    ....................KKKKKKKK..................
    ..................KKOOOOOOOOK.................
    .................KOOOOOOOOOOOK................
    ................KOOOOOOOOOOOOOK...............
    ...............KOOOOOKKKKKOOOOK...............
    ...............KOOOOK.....KOOOOK..............
    ..............KOOOOK.......KOOOK..............
    ..............KOOOOK.......KOOOK..............
    ..............KKKKK........KOOOK..............
    ..........................KOOOOK..............
    .KKKKKKKKKKKKKKKKKKKKKKKKKOOOOKKKKKKKKKKKKKKK.
    KWWWWWWWWWWWWKWWWWWWWWWWKOOOOKKWWWWWWWWWWWWWWK
    KWWWWWWWWWWWWKWWWWWWWWWKOOOOKKWWWWWWWWWWWWWWWK
    KWWWWWWWWWWWWKWWWWWWWWKOOOOKWKWWKKKKKKKKKKKWWK
    KWWWWWWWWWWWWKWWWWWWWWKOOOKWWKWWWWWWWWWWWWWWWK
    KWWWWWWWWWWWWKWWWWWWWKOOOOKWWKWWWWWWWWWWWWWWWK
    KWWOOWWWWWWWWKWWWWWWWKOOOKWWWKWWWWWWWWWWWOOWWK
    KWWOOWWWWWWWWKWWWWWWKOOOKWWWWKWWWWWWWWWWWOOWWK
    KWWWWWWWWWWWWKWWWWWWKOOOKWWWWKWWWWWWWWWWWWWWWK
    .KWWKKKKKKKKKKKKKKKKKOOOKKKKKKKKKKKKKKKKKKWWK.
    ..KK................KOOOK.................KK..
    ....................KKKKK.....................
    ..............................................
    .....................KKK......................
    ....................KOOOK.....................
    ....................KOOOK.....................
    .....................KKK......................
  `,
};
